# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/block_ram/block_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_ram || ORIG_REF_NAME==block_ram} -quiet] -quiet
