# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vittorio/GitHub/CustomCPU/IP/project/CustomCPU_v1_0_project/CustomCPU_v1_0_project.srcs/sources_1/ip/block_ram/block_ram.xci
# IP: The module: 'block_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vittorio/GitHub/CustomCPU/IP/project/CustomCPU_v1_0_project/CustomCPU_v1_0_project.gen/sources_1/ip/block_ram/block_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/vittorio/GitHub/CustomCPU/IP/project/CustomCPU_v1_0_project/CustomCPU_v1_0_project.srcs/sources_1/ip/block_ram/block_ram.xci
# IP: The module: 'block_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vittorio/GitHub/CustomCPU/IP/project/CustomCPU_v1_0_project/CustomCPU_v1_0_project.gen/sources_1/ip/block_ram/block_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
