# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vittorio/GitHub/CustomCPU/customCPU.srcs/sources_1/ip/register_array/register_array.xci
# IP: The module: 'register_array' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vittorio/GitHub/CustomCPU/customCPU.gen/sources_1/ip/register_array/register_array_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'register_array'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/vittorio/GitHub/CustomCPU/customCPU.srcs/sources_1/ip/register_array/register_array.xci
# IP: The module: 'register_array' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vittorio/GitHub/CustomCPU/customCPU.gen/sources_1/ip/register_array/register_array_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'register_array'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
